### ISSUE TITLE
"1001 errors" with merging places.sqlite

### ISSUE THREAD

**Issue by IsaacWeiss** [crazy-max/firefox-history-merger#10]
Attempting to merge two histories, both from Firefox 64.0, using release 1.64.0 on macOS 10.12. Output:

```
Checking and opening DBs...

Master DB is 'places.sqlite'
Backing up 'places.sqlite' to 'places.sqlite.20181217145748'

The following tables will be merged:
- moz_places
- moz_historyvisits (inc. in moz_places)
- moz_origins

Looking for *.sqlite DBs in 'other_places_folder/'
1 valid DB(s) found:
- places-old.sqlite (161247 entries ; last used on 2018-12-17 14:44:51)

## Merging DB 'places-old.sqlite'...
moz_places 1000 / 1000 [============================================] 100.00% 3s
moz_origins 10889 / 10889 [========================================] 100.00% 50s

1001 error(s) occurred. Check your merge.log file

Optimizing places.sqlite database...
```
The resulting places.sqlite file is actually smaller than either of the original two. None of the older history is present.

Merge log: [merge.log](https://github.com/crazy-max/firefox-history-merger/files/2687680/merge.log) Help would be much appreciated!

**Comment by crazy-max** [comment]
@IsaacWeiss I will take a look, thanks for your input

**Comment by crazy-max** [comment]
@IsaacWeiss Can you type this command with the latest release and post logs please. Thanks.

`firefox-history-merger merge --limit 1000 --merge-full other_places_folder/`

**Comment by IsaacWeiss** [comment]
Assuming you meant
`firefox-history-merger merge --limit 1000 --merge-full places.sqlite other_places_folder/`:
Exact same Terminal output, log file attached.
[merge.log](https://github.com/crazy-max/firefox-history-merger/files/2705753/merge.log)

**Comment by crazy-max** [comment]
Ok thx, can you give me the output of the terminal ?
There must be the schema version displayed for `places-old.sqlite`

**Comment by IsaacWeiss** [comment]
```
Checking and opening DBs...

Master DB is 'places.sqlite'
Backing up 'places.sqlite' to 'places.sqlite.20181224194541'

The following tables will be merged:
- moz_places
- moz_historyvisits (inc. in moz_places)
- moz_origins

Looking for *.sqlite DBs in 'other_places_folder/'
1 valid DB(s) found:
- places-old.sqlite (firefox 64 v52 ; 161247 entries ; last used on 2018-12-17 14:44:51)

## Merging DB 'places-old.sqlite'...
moz_places 1000 / 1000 [============================================] 100.00% 9s
moz_origins 10889 / 10889 [========================================] 100.00% 55s

1001 error(s) occurred. Check your merge.log file

Optimizing places.sqlite database...

```

**Comment by crazy-max** [comment]
Your main db `places.sqlite` seems to have a missing column (`favicon_id`) in `moz_places` table.
I suggest to copy `places.sqlite` in a new instance of Firefox 64, launch Firefox and check if the table is populated with the column.

**Comment by p0358** [comment]
Still doesn't seem to work. Database schema v52 (v53 also doesn't work)
![image](https://user-images.githubusercontent.com/5182588/60775931-5a76a700-a128-11e9-8a43-3c2b8ced6bbc.png)

**Comment by crazy-max** [comment]
Hi @p0358, can you check the latest release ?
