### ISSUE TITLE
favicon_id column does not exist in moz_places

### ISSUE THREAD

**Issue by joshieecs** [crazy-max/firefox-history-merger#17]
error.log had errors with this message for every row: 
`msg="Updating moz_places row with id=1 : no such column: favicon_id"`

The schema is not correct. favicon_id does not exist anymore.

Try this: 
Create a new profile with FF 65 or higher. The profile will create places.sqlite file where the moz_places table **_does not_** have a favicon_id column.

Please see [Database.cpp#2075](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/places/Database.cpp#2075) where all data in favicon_id would set to NULL anyway with V37 migration. 

Since sqlite does not support ALTER TABLE DROP COLUMN I assume if you migrate an old places.sqlite from an older FF version the favicon_id column will remain with NULL values. But newly created places.sqlite no longer have the column.

**Comment by crazy-max** [comment]
Hi @joshieecs, thanks for the info, can you create a proper [bug report](https://github.com/crazy-max/firefox-history-merger/issues/new?template=bug_report.md) and put your logs please ?

**Comment by IsaacWeiss** [comment]
I guess this accounts for issue #10?

**Comment by crazy-max** [comment]
I think this is the case @IsaacWeiss, I will improve the process because it seems to be a recurring problem.

**Comment by crazy-max** [comment]
@joshieecs Can you give a try with the latest release?
