### ISSUE TITLE
Convert old schemas to attend current release of firefox-history-merger

### ISSUE THREAD

**Issue by Gabarito007** [crazy-max/firefox-history-merger#19]
### Behaviour
Hi.

It's not exactly a bug, but a request for some help about how to convert old "places.sqlite" to v39.

When I run the program, error message says that my history's schema is v26 and can't go on if schema is not v39 or above.

So, I had searched for conversion tools to do that, without success.

Because I'm not an expert in SQLite, I'm not sure if to export to other format and import back using [SQLiteBrowser](https://sqlitebrowser.org/) would do the job.
Tests I tried here doing that went wrong all of them.
Also, I don't know DataPump tools or other way to convert such data.
Or even to try SQL commands like "Select * from...", inside SQLiteBrowser.

As I said before, I'm newbie on SQL and don't know how to work with my old histories.

I noticed that Nirsoft [MZHistoryView](http://www.nirsoft.net/utils/mozilla_history_view.html) can display all the records of v26 schema.
But Firefox 68.0.1 can't. Worst: it empties the history completely.

If there are some solutions regarding to run old Firefox versions, I'm able to do that.

### Configuration

* Firefox version: 68.0.1 (Quantum)
* Operating system: Windows 7 Ultimate 64 bits
* firefox-history-merger version: 2.1.1

Thank you.

**Comment by crazy-max** [comment]
Hi @Gabarito007,

This is a Firefox 35/36 with this kind of schema version right ?
If so, you can gradually update your schema up to Firefox 68 starting with :

* Firefox 36
* Firefox 37
* Firefox 39
* Firefox 41
* Firefox 48
* Firefox 49
* Firefox 50
* Firefox 55
* Firefox 58
* Firefox 60
* Firefox 68

It's going to take you a while, but it might work. You can find all Firefox releases [here](http://ftp.mozilla.org/pub/firefox/releases/).

**Comment by Gabarito007** [comment]
> This is a Firefox 35/36 with this kind of schema version right ?
> If so, you can gradually update your schema up to Firefox 68 starting with :

Hi, crazy-max.

Thank you for your attention.

What do you mean with update schema along FF versions?
I'd do that very happy, no matter how long it takes.

**Comment by Gabarito007** [comment]
> What do you mean with update schema along FF versions?

I think, I got it.
Is it to open places.sqlite with FF 36 and then open it with FF 37, ... til FF 68?

**Comment by crazy-max** [comment]
> Is it to open places.sqlite with FF 36 and then open it with FF 37, ... til FF 68?

Yes that's it!

**Comment by Gabarito007** [comment]
> 
> 
> > Is it to open places.sqlite with FF 36 and then open it with FF 37, ... til FF 68?
> 
> Yes that's it!

I'll do that and will came back here to report what I got.
Thanks.
:)

**Comment by Gabarito007** [comment]
Hi, crazy-max.

I have several folders with old profiles.
I could update the oldest one to schema v41, that firefox-history-merger can handle.
It was v26 to v41.
Good job.

But another one, which was schema v30 could go to v32, but can't go ahead.
It is recognized by FF 49.0 but if I install FF 50.0, it creates another "places.sqlite", empty, and renames original to "places.sqlite.corrupt".
I tried with FF 49.0.2, supposed to be beyond 49.0.
It recognizes places.sqlite. But happens to occurs the same if I install FF 50.0.
I don't know how to update this "places.sqlite" to v41 like the other one.
Is there some FF between 49.0.2 and 50.0? That could do the job, being a bridge?

One question:
I noticed that if I try to get informations about one file, firefox-history-merger writes and changes it, few bytes at the header.
`firefox-history-merger info places.sqlite`
Why such things happens?

One note:
When I see the amount of records of each "places.sqlite" I get different numbers.
MZHistoryView gives me the biggest one.
firefox-history-merger gives me a smaller number.
Firefox History GUI gives me the smallest of all.

**Comment by crazy-max** [comment]
You can try [this](https://superuser.com/a/436077).

**Comment by Gabarito007** [comment]
> You can try [this](https://superuser.com/a/436077).

Wow!
It's a big tutorial and, as I could see so far, a very good one!
Exactly what I need to work on old history files.
Later, I'll be back to report what I got.
👍

**Comment by crazy-max** [comment]
> Later, I'll be back to report what I got.

Yes, keep me informed, I'm closing this issue for now.

**Comment by Gabarito007** [comment]
Hi, crazy-max.

I'm not expert on SQL, but I'm trying to understand it.
Regarding the SuperUser tutorial, I got this:
Dumping database to file, I got some point among the data showing a suspect of damage.
I got these lines:

```
INSERT INTO moz_places VALUES(471690,'someSite 1',NULL,'moc.ervilanroj.',1,1,0,NULL,20,1468273011066000,'UOZF2Ib1x3u-',0);
INSERT INTO moz_places VALUES(471691,'someSite1','someTitle1','moc.ervilanroj.',1,0,0,16455,-1,1468273011326000,'e8ci4P4tpgA3',0);
/****** CORRUPTION ERROR *******/
INSERT INTO moz_places VALUES(536451,'someSite2','someTitle2','moc.zaodnum.',1,0,0,17681,100,1487898736533000,'Yn1FxDGUQ-Qn',0);
INSERT INTO moz_places VALUES(536450,'someSite2','someTitle2','moc.zaodnum.',1,0,0,17681,100,1487898702355000,'FBo3SufLiFWE',0);

```
Note that ID's is increasing (471690, 471691), but, after the error line is starts to decreasing (536451, 536450) and goes like this til the end.
I don't know if it's normal.

As said at tutorial:

> The area where the database is damaged is likely to be a small block of rows in this table; the idea here is to skip this damaged area and recover as much data as possible. The start area of such a block is represented in the dump as the row before the ERROR comment appears. Using the ID for this row, we can determine where the database is damaged. We do so by using SELECT statements with the ID as a condition; this process takes some trial and error. For example, if the last ID before the error was 49999, and the error follows, the damaged block starts at ID 50000. Use statements like:
> SELECT id FROM moz_places WHERE id >= 536451;

If I run the commands, I got an empty dump2.sql file.

```
SELECT id FROM moz_places WHERE id >= 536451;
.output dump2.sql
.mode insert
SELECT * FROM moz_places WHERE id >= 536500;
.output stdout
.mode list
```
But remember, my ID's are DEcreasing.
I tried with other ID's ranges. No way.

I don't know if I'm doing right.

But there is another information:
I run the same with a previous schema version (FF 49) and got the same error at the same position.
In fact, dumps files are equals.
And the previous schema file is accepted by FF 49.
And the current schema file (for FF 50) won't be accepted by FF 50.

I'm not sure if the file is actually damaged.
The only I want is to update it in such way your firefox-history-merger can handle.

Any idea?

**Comment by crazy-max** [comment]
Maybe you can try to open and export the db with https://sqlitebrowser.org/

**Comment by SophieFitz** [comment]
> 
> 
> Hi, crazy-max.
> 
> I have several folders with old profiles.
> I could update the oldest one to schema v41, that firefox-history-merger can handle.
> It was v26 to v41.
> Good job.
> 
> But another one, which was schema v30 could go to v32, but can't go ahead.
> It is recognized by FF 49.0 but if I install FF 50.0, it creates another "places.sqlite", empty, and renames original to "places.sqlite.corrupt".
> I tried with FF 49.0.2, supposed to be beyond 49.0.
> It recognizes places.sqlite. But happens to occurs the same if I install FF 50.0.
> I don't know how to update this "places.sqlite" to v41 like the other one.
> Is there some FF between 49.0.2 and 50.0? That could do the job, being a bridge?
> 
> One question:
> I noticed that if I try to get informations about one file, firefox-history-merger writes and changes it, few bytes at the header.
> `firefox-history-merger info places.sqlite`
> Why such things happens?
> 
> One note:
> When I see the amount of records of each "places.sqlite" I get different numbers.
> MZHistoryView gives me the biggest one.
> firefox-history-merger gives me a smaller number.
> Firefox History GUI gives me the smallest of all.



Hi Gabarito007!

I'm actually in the process of developing a comprehensive Python project for transferring all browser history and bookmarks, from any version to any version of Firefox. Literally. Well, as far back as Firefox 3.0 when Mozilla changed over to .sqlite storage. I'm still working out the creases. Right now I'm working on how to copy favicons from sqlite DBs older than Firefox 55, to ones newer than 55. It's proving, interesting! 

Each favicon url is individually hashed. I've looked over the sourcecode, my God it's complex! Way beyond my understanding and the level of effort I'm willing to put in at this stage. I'd have to replicate the C++ code in Python, yeah no. I have a workaround. Just when I figured out how to get the icon widths! Then this happens :( 

I would say PM me for updates, but there's no option for that on Github anymore apparently! Just add another comment here, and I'll link my project once it's done.

Weird how your DB got corrupted between 49.0 and 50.0. Fear not, hopefully you'll have a super-easy solution from me soon! 

Josh :)

**Comment by Gabarito007** [comment]
> Hi Gabarito007!

Hi Josh Brenner


> I'm actually in the process of developing a comprehensive Python project for transferring all browser history and bookmarks, from any version to any version of Firefox.

Very cool!

> Each favicon url is individually hashed. I've looked over the sourcecode, my God it's complex!

I believe in you it's complex.  🙂 

> I would say PM me for updates, but there's no option for that on Github anymore apparently! Just add another comment here, and I'll link my project once it's done.

Wonderful idea to keep in touch during the development of your project.
I may be your beta tester for sure.
Please, feel free to sent me a message to my personal e-mail, gabarito007 at gmail dot com.
 
> Weird how your DB got corrupted between 49.0 and 50.0. Fear not, hopefully you'll have a super-easy solution from me soon!

I'm anxious to see that and can't wait.
(rubbing hands) 🙂 🙂 🙂

> Josh :)

Gab Arito.
