### ISSUE TITLE
repair-favicons fails wth panic: runtime error

### ISSUE THREAD

**Issue by medikoo** [crazy-max/firefox-history-merger#2]
When I tried to merge dbs (with `merge`). I got hundreds of logs as follows:

```
(no such table: moz_favicons) 
[2018-01-25 10:00:53]  
```

Therefore I stopped the operation and tried to run `repair-favicons` on database, but it crahed as:

```
$ ./firefox-history-merger-darwin repair-favicons places-2017.sqlite 
Backing up 'places-2017.sqlite' to 'places-2017.sqlite.20180125095857'
Places to check: 141081
Last moz_favicons.id: 0

(no such table: moz_favicons) 
[2018-01-25 09:58:57]  

## Repairing favicons...
 0 / 141081 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x400254c]

goroutine 62 [running]:
sync/atomic.AddUint64(0x16ae84ac, 0x1, 0x0, 0x1, 0x16ae8418)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/mat/besticon/vendor/github.com/golang/groupcache.(*AtomicInt).Add(0x16ae84ac, 0x1, 0x0)
	/go/src/github.com/mat/besticon/vendor/github.com/golang/groupcache/groupcache.go:470 +0x2b
github.com/mat/besticon/vendor/github.com/golang/groupcache.(*Group).Get(0x16ae8400, 0x4495b60, 0x16d78188, 0x16d84100, 0x33, 0x46e3e00, 0x16d802e0, 0x28, 0x0)
	/go/src/github.com/mat/besticon/vendor/github.com/golang/groupcache/groupcache.go:207 +0x66
github.com/mat/besticon/besticon.resultFromCache(0x16adde30, 0x28, 0x28, 0x16adde30, 0x28, 0x400e58f, 0x16d7c130)
	/go/src/github.com/mat/besticon/besticon/caching.go:28 +0x295
github.com/mat/besticon/besticon.(*IconFinder).FetchIcons(0x16a37c60, 0x16adde30, 0x28, 0x11, 0x0, 0x1b178000, 0x0, 0x4980000)
	/go/src/github.com/mat/besticon/besticon/besticon.go:73 +0x80
github.com/crazy-max/firefox-history-merger/utils.GetFavicon(0x16adde30, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/crazy-max/firefox-history-merger/utils/net.go:14 +0x5f
github.com/crazy-max/firefox-history-merger/cmd.repairFavicons.func1(0x16a96f60, 0x16a96f70, 0x16a160a0, 0x16addb3f, 0x12, 0x16a14140, 0x40, 0x27, 0x39, 0x41fff, ...)
	/go/src/github.com/crazy-max/firefox-history-merger/cmd/repair-favicons.go:140 +0x27c
created by github.com/crazy-max/firefox-history-merger/cmd.repairFavicons
	/go/src/github.com/crazy-max/firefox-history-merger/cmd/repair-favicons.go:184 +0xb62
```

**Comment by crazy-max** [comment]
Hi @medikoo, can you read and apply the [SUPPORT page](https://github.com/crazy-max/firefox-history-merger/blob/master/.github/SUPPORT.md) please ? Thanks.

**Comment by medikoo** [comment]
Sure.

### Behaviour

#### Steps to reproduce this issue

1. Run `firefox-history-merger-darwin repair-favicons places.sqlite` (on specific `places.sqlite`, I can provide this file if needed)

#### Expected behaviour

To not crash, and repair favicons or return meaningful error informatoin

#### Actual behaviour

Crashes with `panic: runtime error`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x400254c]

goroutine 62 [running]:
sync/atomic.AddUint64(0x16ae84ac, 0x1, 0x0, 0x1, 0x16ae8418)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/mat/besticon/vendor/github.com/golang/groupcache.(*AtomicInt).Add(0x16ae84ac, 0x1, 0x0)
	/go/src/github.com/mat/besticon/vendor/github.com/golang/groupcache/groupcache.go:470 +0x2b
github.com/mat/besticon/vendor/github.com/golang/groupcache.(*Group).Get(0x16ae8400, 0x4495b60, 0x16d78188, 0x16d84100, 0x33, 0x46e3e00, 0x16d802e0, 0x28, 0x0)
	/go/src/github.com/mat/besticon/vendor/github.com/golang/groupcache/groupcache.go:207 +0x66
github.com/mat/besticon/besticon.resultFromCache(0x16adde30, 0x28, 0x28, 0x16adde30, 0x28, 0x400e58f, 0x16d7c130)
	/go/src/github.com/mat/besticon/besticon/caching.go:28 +0x295
github.com/mat/besticon/besticon.(*IconFinder).FetchIcons(0x16a37c60, 0x16adde30, 0x28, 0x11, 0x0, 0x1b178000, 0x0, 0x4980000)
	/go/src/github.com/mat/besticon/besticon/besticon.go:73 +0x80
github.com/crazy-max/firefox-history-merger/utils.GetFavicon(0x16adde30, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/crazy-max/firefox-history-merger/utils/net.go:14 +0x5f
github.com/crazy-max/firefox-history-merger/cmd.repairFavicons.func1(0x16a96f60, 0x16a96f70, 0x16a160a0, 0x16addb3f, 0x12, 0x16a14140, 0x40, 0x27, 0x39, 0x41fff, ...)
	/go/src/github.com/crazy-max/firefox-history-merger/cmd/repair-favicons.go:140 +0x27c
created by github.com/crazy-max/firefox-history-merger/cmd.repairFavicons
	/go/src/github.com/crazy-max/firefox-history-merger/cmd/repair-favicons.go:184 +0xb62
```

### Configuration

**Firefox version**: 58.0 64bits

**Operating system**: macOS 10.13.2

**firefox-history-merger**: v0.1.1

**Comment by crazy-max** [comment]
Hi @medikoo, thanks for this report!

I've found that Mozilla had removed the `moz_favicons` table and moved this to a new database called `favicons.sqlite`. And yes if you can, can you send me your places.sqlite file please ?

**Comment by medikoo** [comment]
>And yes if you can, can you send me your places.sqlite file please ?

Which way (I would prefer to not attach it to the issue, in public repository) ?

**Comment by crazy-max** [comment]
@medikoo By email at webmaster[@]crazyws.fr
Thanks

**Comment by medikoo** [comment]
> By email

Sent!

**Comment by crazy-max** [comment]
@medikoo Ok after investigation there is an issue like i said before about `moz_favicons` table.
I will make a new release to fix that asap.
Thanks for your report!

**Comment by crazy-max** [comment]
@medikoo It is related to [besticon](https://github.com/mat/besticon) and caching implementation. This will be solved in the next release.

**Comment by crazy-max** [comment]
Can you try the latest release? Thanks!

**Comment by medikoo** [comment]
I've tried to run it on my places files, and now I got an error:
```
Checking and opening DBs...
CRIT Your database schema v39 is not compatible with the current implementation (Firefox 58)
```

**Comment by crazy-max** [comment]
@medikoo Schema v39 is linked to Firefox 57 and the latest release of firefox-history-merger is based on schame v41 (Firefox 58). You can use release [1.57.2](https://github.com/crazy-max/firefox-history-merger/releases/tag/1.57.2) or upgrade to Firefox 58

**Comment by medikoo** [comment]
> You can use release 1.57.2

Isn't the one that crashed with error with which this issue started?

>  or upgrade to Firefox 58

I want to merge schema, copied from instance that's no longer used. I cannot upgrade it to FF 58, as computer is dead

**Comment by crazy-max** [comment]
> Isn't the one that crashed with error with which this issue started?

No this was the previous one (0.1.1)

> I want to merge schema, copied from instance that's no longer used. I cannot upgrade it to FF 58, as computer is dead

Ok i understand, but you can simply copy your places.sqlite and favicons.sqlite files in a new profile of Firefox 58, start Firefox 58 then database will be migrated, close Firefox 58 and copy back the updated sqlite files.
I will try to implement the Firefox migration process of databases in the next release
