### ISSUE TITLE
Does not work with Firefox ESR

### ISSUE THREAD

**Issue by Coronatus** [crazy-max/firefox-history-merger#20]
### Behaviour

Great and uncomplicated tool to get this done, thank you so much for sharing! :-) It does not seem to work with Firefox 60.8.0 though. Maybe the tool fails to detect its version properly? Firefox 60.8.0 is the current esr-release.

#### Steps to reproduce this issue

<pre><font color="#8AE234"><b>user@ubuntu</b></font>:<font color="#729FCF"><b>~/.mozilla/firefox</b></font>$ ./firefox-history-merger-2.1.1 info e3gpock7.default/places.sqlite 
<font color="#555753">Fri, 23 Aug 2019 18:36:06 CEST</font> <font color="#4E9A06">INF</font> Schema version:         v43 (Firefox &gt;= 60)
<font color="#555753">Fri, 23 Aug 2019 18:36:06 CEST</font> <font color="#4E9A06">INF</font> Compatible:             true
<font color="#555753">Fri, 23 Aug 2019 18:36:06 CEST</font> <font color="#4E9A06">INF</font> Places entries:         134027
<font color="#555753">Fri, 23 Aug 2019 18:36:06 CEST</font> <font color="#4E9A06">INF</font> Historyvisits entries:  238089
<font color="#555753">Fri, 23 Aug 2019 18:36:06 CEST</font> <font color="#4E9A06">INF</font> Last used on:           2019-06-01 23:04:32
</pre>

<pre><font color="#8AE234"><b>user@ubuntu</b></font>:<font color="#729FCF"><b>~/.mozilla/firefox</b></font>$ ./firefox-history-merger-2.1.1 info 3zy3fc18.default/places.sqlite
<font color="#555753">Fri, 23 Aug 2019 18:36:17 CEST</font> <font color="#4E9A06">INF</font> Schema version:         v43 (Firefox &gt;= 60)
<font color="#555753">Fri, 23 Aug 2019 18:36:17 CEST</font> <font color="#4E9A06">INF</font> Compatible:             true
<font color="#555753">Fri, 23 Aug 2019 18:36:17 CEST</font> <font color="#4E9A06">INF</font> Places entries:         27684
<font color="#555753">Fri, 23 Aug 2019 18:36:17 CEST</font> <font color="#4E9A06">INF</font> Historyvisits entries:  50122
<font color="#555753">Fri, 23 Aug 2019 18:36:17 CEST</font> <font color="#4E9A06">INF</font> Last used on:           2019-08-23 18:34:06
</pre>

<pre><font color="#8AE234"><b>user@ubuntu</b></font>:<font color="#729FCF"><b>~/.mozilla/firefox</b></font>$ ./firefox-history-merger-2.1.1 merge 3zy3fc18.default/places.sqlite e3gpock7.default/places.sqlite 
<font color="#555753">Fri, 23 Aug 2019 18:36:43 CEST</font> <font color="#4E9A06">INF</font> 134027 places will be merged
<font color="#555753">Fri, 23 Aug 2019 18:36:43 CEST</font> <font color="#4E9A06">INF</font> Merging 1000 places (1/135)...
<font color="#555753">Fri, 23 Aug 2019 18:36:43 CEST</font> <font color="#EF2929"><b>ERR</b></font> Updating moz_places row <font color="#CC0000">error=&quot;no such column: origin_id&quot;</font> <font color="#06989A">left=</font>134027 <font color="#06989A">mplaces_id=</font>6 <font color="#06989A">places_id=</font>23 <font color="#06989A">url=</font>http://www.mozilla.com/de/firefox/help/
<font color="#555753">Fri, 23 Aug 2019 18:36:43 CEST</font> <font color="#EF2929"><b>ERR</b></font> Updating moz_places row <font color="#CC0000">error=&quot;no such column: origin_id&quot;</font> <font color="#06989A">left=</font>134026 <font color="#06989A">mplaces_id=</font>7 <font color="#06989A">places_id=</font>24 <font color="#06989A">url=</font>http://www.mozilla.com/de/firefox/customize/
</pre>

(snip... the list goes on and on)

### Configuration

* Firefox version / arch (ex. 62.0 64bits) : Firefox 60.8 ESR 64-bit (current version)
* Operating system (ex. Windows 10 Pro 64 bits) : Linux Mint 19.2 Tina
* firefox-history-merger version (ex. 2.0.0) : 2.1.1

I have tried all versions currently released. I already tried to launch the profile with Firefox 68 (the current live release) but there neither profile seems to load at all, I get a message that I have to use Firefox Accounts instead if I want to keep my previous data. Odd.

**Comment by crazy-max** [comment]
@Coronatus Before digging into your issue, Mozilla has changed his release process. The current ESR release is 68.0.2esr :

* `08-Jul-2019`: [60.8.0esr](http://ftp.mozilla.org/pub/firefox/releases/60.8.0esr/)
* `18-Jul-2019`: [68.0.1esr](http://ftp.mozilla.org/pub/firefox/releases/68.0.1esr/)
* `14-Aug-2019`: [68.0.2esr](http://ftp.mozilla.org/pub/firefox/releases/68.0.2esr/)

Maybe you could try the latest release?

And thanks for your support :)

**Comment by Coronatus** [comment]
Thank you for the quick reply!

Firefox 68 ESR is as of the time I'm writing this in its "Qualify" stage which is not recommended for productive environments if remember correctly. I usually download firefox-esr through the official mozillateam ppa which does not offer it yet either.

However, I went and downloaded Firefox 68 ESR directly from the official sources and gave it a shot. It behaves just like Firefox 68 Live... it refuses to load my profile(s) altogether, creates a new, empty profile and only displays a message that I need to sign up to Firefox Accounts if I want to keep my profile data. How that is supposed to help in any way, I have no clue. Sounds a bit fishy.

I will try the following for now:

* Update my Firefox 60 ESR to Firefox 61 Live.
* Do the fool's walk all the way up to FX 68 Live.
* Attempt another profile merger.
* Migrate FX 68 Live to FX 68 ESR.

I will report back if I find out anything new. Thanks for now! :-)

**Comment by crazy-max** [comment]
> Firefox 68 ESR is as of the time I'm writing this in its "Qualify" stage which is not recommended for productive environments if remember correctly. I usually download firefox-esr through the official mozillateam ppa which does not offer it yet either.

You right! Very strange mozilla brings those releases publicly.

> However, I went and downloaded Firefox 68 ESR directly from the official sources and gave it a shot. It behaves just like Firefox 68 Live... it refuses to load my profile(s) altogether, creates a new, empty profile and only displays a message that I need to sign up to Firefox Accounts if I want to keep my profile data. How that is supposed to help in any way, I have no clue. Sounds a bit fishy.

That's odd yeah.

> I will report back if I find out anything new. Thanks for now! :-)

Thanks for your involvement, I will take a look too. Let me know.

**Comment by Coronatus** [comment]
Hey... so I got it to work, here's what I did:

1. I downloaded the SQLite DevTools and inspected both databases. Although both profiles are listed as Version 43 in the profile merging tool, they did have several structural differences:

* The table moz_origins was missing altogether from the new profile.
* The table moz_places was missing the column origin_id
* The missing column origin_id had an identity in the older db. It was missing too (obviously).
* The foreign key constraints were missing as well, obviously.

2. I went ahead and created the missing structures in the new places.sqlite file.

3. I tried to use the tool again... it worked!

Out of curiosity I then went ahead and dug a little deeper... here's what I found out.

* If I let Firefox create a completely new profile from scratch, it is created without the moz_origins table, the constraints, index and the column origin_id in moz_places. 

* In the old places.sqlite file the origins_id column was (mostly) empty. Apparently this is an old, defunct structure. On very old history entries this column contained the foreign key to the corresponding moz_origins table. At some point this just ended however, and the column only contained NULL values. The final history entry to contain an origin_id in my profile was me browsing the changelog of a new Firefox version. Go figure. :-)

* I then had the crazy idea of deploying the tool again, but this time merging the new places.sqlite file into the old one. **This works too!**

Thanks again... cheers! :+1:

**Comment by crazy-max** [comment]
@Coronatus Thanks for your feedback :bowing_man:
It was instructive and I think it will help other users.
