### ISSUE TITLE
Merge Older places.sqlite Files

### ISSUE THREAD

**Issue by meyertet** [crazy-max/firefox-history-merger#3]
Hi Max,

thank you very much for developing firefox-history-merger ? Ist there a possibility to merge also older places.sqlite files (ie v30 firefox 47.0.2).

Thank you for your response
meyertet

**Comment by crazy-max** [comment]
Hi @meyertet,

Yes it is quite possible to merge old versions of places.sqlite files. You just need to have the sqlite you want to merge compatible with the version supported by firefox-history-merger. To find out you can use the `info` command.

I myself have made some merges on sqlites based on Firefox version 40 so it should be fine but don't hesitate to tell me if you have any issues.

Thanks
