### ISSUE TITLE
MacOS 10.15 - zsh: bad CPU type in executable

### ISSUE THREAD

**Issue by marcodome** [crazy-max/firefox-history-merger#35]
### Behaviour
I suppose the program it isn't compatible with MacOS 10.15 (Catalina): is it because it allows only 64 bit application? (not sure if this is applicable to terminal programs)

#### Steps to reproduce this issue
1. ./firefox-history-merger-darwin-10.6-386

#### Expected behaviour
(the usage of firefox-history-merger-darwin-10.6-386)

#### Actual behaviour
the only output in the shell was:
zsh: bad CPU type in executable: ./firefox-history-merger-darwin-10.6-386
or
bash: ./firefox-history-merger-darwin-10.6-386: Bad CPU type in executable

### Configuration

* Firefox version / arch (ex. 62.0 64bits) : - 
* Operating system (ex. Windows 10 Pro 64 bits) : MacOs 10.15.4 (Catalina)
* firefox-history-merger version (ex. 2.0.0) : 2.8.0

### Extra thoughts
I have the old machine with MacOs 10.13 (High Sierra) and the program run perfectly there: so, thank you a lot!!

**Comment by crazy-max** [comment]
@marcodome Will take a look, thanks for your input!

**Comment by crazy-max** [comment]
@marcodome To solve this it's recommended to download darwin-10.6-amd64 or linux-amd64 release.
