### ISSUE TITLE
Obsolete database versions conflict

### ISSUE THREAD

**Issue by git6578** [crazy-max/firefox-history-merger#5]
Tried to merge '12 '15 '18 history.
My use case probably doesn't match.
Anywhere I can go from here?

![12rbbvt](https://user-images.githubusercontent.com/1951866/40772601-b6c34c02-64c0-11e8-85df-4d0071152c62.png)

Bonus: Is there a way to merge Firefox 'places.sqlite' with Chrome 'History' database? )

**Comment by crazy-max** [comment]
You can merge your db `places0.sqlite` (compatible) with `places1.sqlite` and `places2.sqlite`.
Copy `places1.sqlite` and `places2.sqlite` in `Desktop\some_places_to_merge` and type :

```
firefox-history-merger merge "places0.sqlite" "some_places_to_merge/" --merge-full
```

**Comment by git6578** [comment]
thank you, let's keep this solution around for the next one. (my solution was the FF norwell history plugin, which merged all Firefox and Chromium History files.)
