### ISSUE TITLE
Question about database schema

### ISSUE THREAD

**Issue by venteto** [crazy-max/firefox-history-merger#54]
I'm trying to create an unrelated utility for my own use, and I wondered how you are finding the current schema version number and entity relationship diagram (mainly of the places.sqlite database when Mozilla changes it? I've found one ERD on their wiki but it seems pretty out of date just from manually browsing the tables (2009 I believe).

**Comment by crazy-max** [comment]
@derrgill 

> I wondered how you are finding the current schema version number

https://github.com/crazy-max/firefox-history-merger#databases-schema

> and entity relationship diagram

I export the schema from the `places.sqlite`  file you can found in your profile folder.
