### ISSUE TITLE
Incompatible with Firefox 61

### ISSUE THREAD

**Issue by xianwenchen** [crazy-max/firefox-history-merger#6]
Thank you for sharing the software!

In Firefox 61, the program tells me that

 ` Schema version:   v47 (Firefox >= -1)`

Could you check whether there is significant work to be done, to update the software to work with schema version 47? :-)

**Comment by crazy-max** [comment]
Hey @xianwenchen,

Many schema updates through 61 betas. The main difference is the insertion of a new table called `moz_meta` :

> // This table holds key-value metadata for Places and its consumers. Sync stores
> // the sync IDs for the bookmarks and history collections in this table, and the
> // last sync time for history.

This does not impact firefox-history-merger because Firefox is closed during the process. So i think it will be painless :sweat_smile:

And thanks for your support

**Comment by crazy-max** [comment]
Check the latest release ;)

**Comment by xianwenchen** [comment]
Worked like a charm! Thank you very much! I wish you a nice weekend!
