### ISSUE TITLE
 UNIQUE constraint failed: moz_places.guid

### ISSUE THREAD

**Issue by xianwenchen** [crazy-max/firefox-history-merger#7]
Dear author,

I tried to merge two histories and found the following type of errors:

`ERROR Creating moz_places row with id=62119 : UNIQUE constraint failed: moz_places.guid
`
I examined the newly merged history file and realized that the entries with errors are not merged in. I can send you the two history files by email, if that will be needed to debug.

Please let me know.

**Comment by crazy-max** [comment]
Hey @xianwenchen, i will take a look asap. You can send me an email with your places at webmaster [at] crazyws.fr

Thx

**Comment by crazy-max** [comment]
Closed due to inactivity

**Comment by xianwenchen** [comment]
Hi! Thanks! I didn't notice this message until now, strangely. I will test it again and send the history files.
